export interface FaqItem {
  readonly question: string;
  readonly answer: string;
}

/**
 * Single source of truth for FAQ data.
 * Used by both LandingFAQ (UI) and JsonLd (structured data).
 */
export const FAQ_ITEMS: readonly FaqItem[] = [
  {
    question: 'Is AI Resume Pass really free? Are there watermarks on exports?',
    answer:
      'Yes, 100% free with no watermarks — ever. All core features are free for every user: online editing, AI-assisted generation, real-time visual layout, content polishing, and HD PDF export. There are no hidden paywalls or premium download gates.',
  },
  {
    question: 'What is the best format to export my resume?',
    answer:
      'PDF is the gold standard. It preserves your formatting perfectly across devices and is well-parsed by ATS (Applicant Tracking Systems). With AI Resume Pass, you can export a crisp, watermark-free PDF in one click.',
  },
  {
    question: 'I have no internships or projects — what do I write?',
    answer:
      'AI Resume Pass has a built-in guided flow for "zero experience" users. It helps you surface coursework, campus activities, volunteer work, and personal projects, then structures them with the STAR method into professional resume entries.',
  },
  {
    question: 'How can I tailor my resume for different job postings?',
    answer:
      'That\'s one of our strongest features. Paste a job description (JD) and AI automatically rewrites your resume highlights to match. You can generate multiple targeted versions from a single base resume — perfect for applying to different roles simultaneously.',
  },
  {
    question: 'Can I edit my resume on mobile?',
    answer:
      'Yes. AI Resume Pass works on any modern browser — desktop, tablet, or phone. Your data syncs in real-time, so switching devices won\'t lose any content.',
  },
  {
    question: 'Why is AI Resume Pass better than other resume tools?',
    answer:
      'Because it\'s designed specifically for job seekers, not as a generic template tool. Compared to Word, it offers professional resume-specific layouts. Compared to other resume builders, it provides deeper AI integration — generating higher-quality, role-specific content.',
  },
  {
    question: 'What should I do if I run into an issue?',
    answer:
      'You can reach out to us anytime via email or through the feedback page. You\'ll get a response directly from the developer — no chatbots.',
  },
  {
    question: 'Can AI Resume Pass format text generated by ChatGPT or Claude?',
    answer:
      'Absolutely. Use the "Text to Resume" feature — paste resume text generated by ChatGPT, Claude, Gemini, DeepSeek, or any AI tool, and the system will automatically parse it into a structured resume with professional formatting and free PDF export.',
  },
  {
    question: 'Can I use AI to polish individual resume sections?',
    answer:
      'Yes. AI Resume Pass supports section-level AI operations. You can polish a single work experience, project entry, or summary independently. You can also select a target role category so AI adjusts wording and emphasis accordingly.',
  },
  {
    question: 'How is the AI generation different from other tools?',
    answer:
      'Our AI is deeply integrated into the entire resume workflow, not just a text generator. Key differences: 1) Dynamic guided questions based on your background (student/graduate/professional); 2) Role-specific content customization; 3) Section-level generation and polishing; 4) JD matching that rewrites bullet points to align with specific job postings.',
  },
  {
    question: 'What is an ATS-friendly resume? Does AI Resume Pass support it?',
    answer:
      'ATS (Applicant Tracking System) is the software companies use to screen resumes. An ATS-friendly resume requires clear structure, keyword coverage, and parseable PDF format. All AI Resume Pass templates are ATS-tested, and exported PDFs are perfectly parsed by major recruiting platforms like Greenhouse, Lever, Workday, and more.',
  },
  {
    question: 'Which AI models does AI Resume Pass use?',
    answer:
      'AI Resume Pass supports multiple leading AI models including OpenAI GPT and others. You can switch models when generating or importing resumes. All models are available for free.',
  },
  {
    question: 'Is my resume data secure? Will it be used to train AI?',
    answer:
      'Your resume data belongs to you alone. We promise: your data will never be used for AI model training, never shared with any third party, and all transfers are encrypted. You can delete all your data at any time.',
  },
];
