import type { TemplateTaxonomy } from './template-taxonomy'

export interface TemplateMetadata {
  readonly id: string
  readonly name: string
  readonly description: string
  readonly preview: string
  readonly tags: readonly string[]
  readonly taxonomy: TemplateTaxonomy
  readonly visibility: { readonly editor: boolean; readonly catalog: boolean }
}

/** Shared display data only: no React, template components or server dependencies.
 * Taxonomy describes suitability, not a release/ATS certification.
 * Keep historical visibility until separate publication review.
 */
export const TEMPLATE_METADATA = {
  simple: {
    id: 'simple',
    name: '简约',
    description: '简洁大方，适合所有场景',
    preview: '/thumbnails/template_simple.webp',
    tags: ['通用', '简洁'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['general', 'business'],
      styles: ['minimal'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  elegant: {
    id: 'elegant',
    name: '典雅',
    description: '深色头部 + 金色点缀，庄重大方，适合正式场合',
    preview: '/thumbnails/template_elegant.webp',
    tags: ['正式', '庄重', '典雅', '金色'],
    taxonomy: {
      stages: ['experienced'],
      roles: ['general'],
      styles: ['formal'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  warm: {
    id: 'warm',
    name: '双栏',
    description: '双列布局，左侧边栏 + 右侧主内容，淡黄色点缀',
    preview: '/thumbnails/template_warm.webp',
    tags: ['通用', '双列', '淡黄', '侧边栏'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['general', 'business'],
      styles: ['fresh'],
      layouts: ['double'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  timeline: {
    id: 'timeline',
    name: '时间轴',
    description: '左侧日期 + 右侧内容，竖线贯穿，经典时间轴风格',
    preview: '/thumbnails/template_timeline.webp',
    tags: ['通用', '时间轴', '经典', '简洁'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['general', 'business'],
      styles: ['classic'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  lanxin: {
    id: 'lanxin',
    name: '蓝芯',
    description: '浅蓝页眉 + 左侧竖线节点，清爽专业，适合产品、运营与校招场景',
    preview: '/thumbnails/template_lanxin.webp',
    tags: ['通用', '时间轴', '浅蓝', '专业'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['general', 'business'],
      styles: ['fresh'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: false, catalog: false },
  },
  tablegrid: {
    id: 'tablegrid',
    name: '表格',
    description: '传统表格结构，信息分区清晰，适合正式投递与标准化简历',
    preview: '/thumbnails/template_tablegrid.webp',
    tags: ['通用', '表格', '正式', '标准'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['general'],
      styles: ['formal'],
      layouts: ['table'],
      densities: ['compact'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  xinghe: {
    id: 'xinghe',
    name: '星河',
    description:
      '紫色渐变点缀 + 大气单栏，适合产品、运营、市场与互联网通用岗位',
    preview: '/thumbnails/template_xinghe.webp',
    tags: ['原创', '通用', '精美', '大气'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['general', 'business'],
      styles: ['fresh'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  lifeng: {
    id: 'lifeng',
    name: '砺锋',
    description: '深色侧栏 + 紧凑信息布局，适合技术、工程、项目管理与咨询岗位',
    preview: '/thumbnails/template_lifeng.webp',
    tags: ['原创', '紧凑', '双栏', '技术'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['technical'],
      styles: ['business'],
      layouts: ['double'],
      densities: ['compact'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  qingsui: {
    id: 'qingsui',
    name: '青穗',
    description: '青蓝渐变页眉 + 校招亮点区，适合应届生、实习和转专业求职',
    preview: '/thumbnails/template_qingsui.webp',
    tags: ['原创', '校招', '应届生', '清爽'],
    taxonomy: {
      stages: ['internship', 'graduate'],
      roles: ['general', 'business'],
      styles: ['fresh'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  yuanshan: {
    id: 'yuanshan',
    name: '远山',
    description: '章节索引与履历正文分轨，适合资深专家和管理岗位；只展示已填写的真实业绩',
    preview: '/thumbnails/template_yuanshan.webp',
    tags: ['原创', '资深', '管理', '稳重'],
    taxonomy: {
      stages: ['executive', 'experienced'],
      roles: ['general', 'business'],
      styles: ['business', 'formal'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  hengjian: {
    id: 'hengjian',
    name: '衡简',
    description: '正式表格信息 + 端正分区，适合国企、银行、事业单位与传统行业',
    preview: '/thumbnails/template_hengjian.webp',
    tags: ['原创', '正式', '国企', '表格'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['general'],
      styles: ['formal'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  yiyetong: {
    id: 'yiyetong',
    name: '一页通',
    description: '极致一页承载，压缩高效，适合海投和信息量较多的用户',
    preview: '/thumbnails/template_yiyetong.webp',
    tags: ['原创', '紧凑', '一页', '海投'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['general', 'technical'],
      styles: ['minimal'],
      layouts: ['single'],
      densities: ['compact'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  lanzhe: {
    id: 'lanzhe',
    name: '蓝折',
    description:
      '蓝色折纸页眉 + 立体签条模块，紧凑精致，适合年轻用户、校招、实习与运营岗位',
    preview: '/thumbnails/template_lanzhe.webp',
    tags: ['原创', '校招', '折角', '紧凑'],
    taxonomy: {
      stages: ['internship', 'graduate'],
      roles: ['general', 'business'],
      styles: ['fresh'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  dense: {
    id: 'dense',
    name: '密排',
    description:
      '青绿时间线 + 极高信息密度，适合内容较多、希望尽量压缩到一页的简历',
    preview: '/thumbnails/template_dense.webp',
    tags: ['原创', '紧凑', '时间轴', '一页'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['general', 'technical'],
      styles: ['minimal'],
      layouts: ['single'],
      densities: ['compact'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  lanjiao: {
    id: 'lanjiao',
    name: '蓝角',
    description: '蓝色几何页眉 + 左侧日期轴，适合产品、运营、市场与综合岗位',
    preview: '/thumbnails/template_lanjiao.webp',
    tags: ['原创', '蓝色', '时间轴', '清爽'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['general', 'business'],
      styles: ['fresh'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  lanmu: {
    id: 'lanmu',
    name: '蓝幕',
    description: '蓝色渐变页眉 + 左侧信息栏，适合产品、运营、市场与综合岗位',
    preview: '/thumbnails/template_lanmu.webp',
    tags: ['原创', '双栏', '蓝色', '清爽'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['general', 'business'],
      styles: ['fresh'],
      layouts: ['double'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  ziji: {
    id: 'ziji',
    name: '紫记',
    description:
      '紫色渐变头图 + 双栏履历笔记，适合个人主页感、运营、产品与创意岗位',
    preview: '/thumbnails/template_ziji.webp',
    tags: ['原创', '双栏', '紫色', '个人履历'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['creative', 'business'],
      styles: ['creative'],
      layouts: ['double'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  lanfa: {
    id: 'lanfa',
    name: '蓝法',
    description: '深蓝法务风格 + 端正信息分区，适合法务、行政与商务支持岗位',
    preview: '/thumbnails/template_lanfa.webp',
    tags: ['原创', '蓝色', '正式', '法务'],
    taxonomy: {
      stages: ['experienced'],
      roles: ['general'],
      styles: ['formal'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  lanying: {
    id: 'lanying',
    name: '蓝营',
    description: '蓝色商务条幅 + 清晰模块标题，适合市场、运营和销售支持岗位',
    preview: '/thumbnails/template_lanying.webp',
    tags: ['原创', '蓝色', '市场', '商务'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['general', 'business'],
      styles: ['fresh'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  qiance: {
    id: 'qiance',
    name: '浅策',
    description: '浅蓝柔和页眉 + 清爽单栏排版，适合策划、运营和校招简历',
    preview: '/thumbnails/template_qiance.webp',
    tags: ['原创', '浅蓝', '策划', '清爽'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['general', 'business'],
      styles: ['fresh'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  heijiao: {
    id: 'heijiao',
    name: '黑教',
    description: '黑白教师风格 + 严谨分区，适合教师、教培和学术类岗位',
    preview: '/thumbnails/template_heijiao.webp',
    tags: ['原创', '黑白', '教师', '正式'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['education'],
      styles: ['classic', 'formal'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  shanglan: {
    id: 'shanglan',
    name: '商蓝',
    description: '蓝紫侧栏 + 商务应届布局，适合应届生、实习和商务通用岗位',
    preview: '/thumbnails/template_shanglan.webp',
    tags: ['原创', '双栏', '应届生', '蓝紫'],
    taxonomy: {
      stages: ['internship', 'graduate'],
      roles: ['general', 'business'],
      styles: ['business'],
      layouts: ['double'],
      densities: ['standard'],
      languages: ['zh'],
    },
    // 保留旧 ID 以兼容已有简历，但“商蓝”与“蓝序”属于同构旧款，
    // 不再占用公开目录名额；公开集合由 template-catalog.ts 派生。
    visibility: { editor: true, catalog: false },
  },
  jinhang: {
    id: 'jinhang',
    name: '金行',
    description: '金色银行风格 + 稳重线条，适合银行、金融和传统行业岗位',
    preview: '/thumbnails/template_jinhang.webp',
    tags: ['原创', '金色', '银行', '金融'],
    taxonomy: {
      stages: ['experienced'],
      roles: ['general'],
      styles: ['formal'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  jijian: {
    id: 'jijian',
    name: '极简黑',
    description: '黑白极简 + 高信息密度，适合希望快速压缩内容的一页简历',
    preview: '/thumbnails/template_jijian.webp',
    tags: ['原创', '黑白', '极简', '一页'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['general', 'technical'],
      styles: ['minimal'],
      layouts: ['single'],
      densities: ['compact'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  lanzix: {
    id: 'lanzix',
    name: '蓝紫',
    description: '蓝紫点线装饰 + 应届生友好排版，适合校招、实习和初级岗位',
    preview: '/thumbnails/template_lanzix.webp',
    tags: ['参考改编', '蓝紫', '校招', '应届生'],
    taxonomy: {
      stages: ['internship', 'graduate'],
      roles: ['general', 'business'],
      styles: ['fresh'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  qingyun: {
    id: 'qingyun',
    name: '青云',
    description:
      '天青蓝 + 暖橙 · 应届毕业徽章 · 双语时间轴 · 校招应届生首选（Headless）',
    preview: '/thumbnails/template_qingyun.webp',
    tags: ['旗舰', '校招', '应届生', '天青蓝', 'Headless'],
    taxonomy: {
      stages: ['internship', 'graduate'],
      roles: ['general', 'business'],
      styles: ['fresh'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: false },
  },
  mashang: {
    id: 'mashang',
    name: '码上',
    description:
      '代码绿 + 终端琥珀 · 终端风 Hero · 章节编号 · 开发者 / 算法岗首选（Headless）',
    preview: '/thumbnails/template_mashang.webp',
    tags: ['旗舰', '开发', '算法', '技术', '终端', 'Headless'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['technical'],
      styles: ['creative'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: false },
  },
  zhumo: {
    id: 'zhumo',
    name: '朱墨',
    description:
      '朱砂红 + 松烟墨 · 衬线字 · 中文数字编号 · 朱红方印 · 编辑 / 文案 / 内容岗首选（Headless）',
    preview: '/thumbnails/template_zhumo.webp',
    tags: ['旗舰', '编辑', '文案', '内容', '衬线', 'Headless'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['creative'],
      styles: ['classic'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: false },
  },
  xingtan: {
    id: 'xingtan',
    name: '杏坛',
    description:
      '杏黄 + 松烟墨 · 古籍卷首双实线 banner · 章节「第壹章」· 书法体姓名 · 教师 / 学术岗首选（Headless）',
    preview: '/thumbnails/template_xingtan.webp',
    tags: ['旗舰', '教师', '学术', '教育', '古籍', 'Headless'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['education'],
      styles: ['classic', 'formal'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: false },
  },
  moxu: {
    id: 'moxu',
    name: '墨序',
    description:
      '大姓名页眉、黑白联系卡与单栏时间线，适合英文商务简历和专业履历',
    preview: '/thumbnails/template_moxu.webp',
    tags: ['英文', '商务', '单栏', '黑白'],
    taxonomy: {
      stages: ['experienced'],
      roles: ['general', 'business'],
      styles: ['minimal', 'business'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh', 'en'],
    },
    visibility: { editor: true, catalog: true },
  },
  qingning: {
    id: 'qingning',
    name: '青柠',
    description:
      '浅绿圆形图标、暖金点线与几何角饰，清爽单栏，适合校招和通用求职',
    preview: '/thumbnails/template_qingning.webp',
    tags: ['清爽', '单栏', '校招', '通用'],
    taxonomy: {
      stages: ['internship', 'graduate'],
      roles: ['general', 'business'],
      styles: ['fresh'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  suxian: {
    id: 'suxian',
    name: '素线',
    description: '黑白细线与窄日期栏，适合教育和校园经历优先的校招简历',
    preview: '/thumbnails/template_suxian.webp',
    tags: ['校招', '应届生', '黑白', '细线'],
    taxonomy: {
      stages: ['internship', 'graduate'],
      roles: ['general', 'business'],
      styles: ['minimal', 'classic'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: false },
  },
  zhangxu: {
    id: 'zhangxu',
    name: '章序',
    description: '深灰蓝页眉与动态章节编号，适合教育、实习和校园经历清晰分节的校招简历',
    preview: '/thumbnails/template_zhangxu.webp',
    tags: ['参考改编', '校招', '应届生', '编号', '商务'],
    taxonomy: {
      stages: ['internship', 'graduate'],
      roles: ['general', 'business'],
      styles: ['business', 'classic'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  mixu: {
    id: 'mixu',
    name: '米序',
    description: '浅米色信息侧栏与连续章节编号，适合设计、内容和创意岗位',
    preview: '/thumbnails/template_mixu.webp',
    tags: ['设计', '创意', '双栏', '编号'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['creative', 'business'],
      styles: ['creative', 'classic'],
      layouts: ['double'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: false },
  },
  chengyan: {
    id: 'chengyan',
    name: '橙研',
    description: '低饱和橙色页头与左侧模块导线，适合产品、研究及项目经历展示',
    preview: '/thumbnails/template_chengyan.webp',
    tags: ['产品', '研究', '项目', '单栏'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['business', 'general'],
      styles: ['fresh', 'business'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: false },
  },
  lanqi: {
    id: 'lanqi',
    name: '蓝栖',
    description: '左侧浅灰经历卡与右侧个人信息栏，适合校招与实习投递',
    preview: '/thumbnails/template_lanqi.webp',
    tags: ['校招', '实习', '双栏', '清爽'],
    taxonomy: {
      stages: ['internship', 'graduate'],
      roles: ['general', 'business'],
      styles: ['fresh', 'business'],
      layouts: ['double'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: false },
  },
  shenke: {
    id: 'shenke',
    name: '深刻',
    description: '深蓝页框与双层章节条，适合技术项目和技能成果的有序展示',
    preview: '/thumbnails/template_shenke.webp',
    tags: ['技术', '项目', '深蓝', '单栏'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['technical'],
      styles: ['business', 'minimal'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: false },
  },
  kuangxu: {
    id: 'kuangxu',
    name: '框序',
    description: '灰白页顶、信息框与分节横框，适合校招经历的清晰陈列',
    preview: '/thumbnails/template_kuangxu.webp',
    tags: ['校招', '实习', '灰白', '单栏'],
    taxonomy: {
      stages: ['graduate', 'internship'],
      roles: ['general', 'business'],
      styles: ['minimal', 'business'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: false },
  },
  huiying: {
    id: 'huiying',
    name: '灰映',
    description: '灰阶横向页眉与左侧联系信息栏，适合运营和内容岗位的实习、校园经历',
    preview: '/thumbnails/template_huiying.webp',
    tags: ['运营', '内容', '实习', '双栏'],
    taxonomy: {
      stages: ['internship', 'graduate'],
      roles: ['business', 'general'],
      styles: ['minimal', 'business'],
      layouts: ['double'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: false },
  },
  jingrui: {
    id: 'jingrui',
    name: '蓝序',
    description:
      '浅灰头像区、蓝紫信息侧栏与独立经历主栏，适合校招应届与通用商务岗位',
    preview: '/thumbnails/template_jingrui.webp',
    tags: ['商务', '校招', '双栏', '教育优先'],
    taxonomy: {
      stages: ['graduate', 'internship'],
      roles: ['general', 'business'],
      styles: ['business'],
      layouts: ['double'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  yunbai: {
    id: 'yunbai',
    name: '云白',
    description: '黑白横向页眉与点线分区，保留宽松单栏阅读节奏',
    preview: '/thumbnails/template_yunbai.webp',
    tags: ['参考改编', '通用', '黑白', '点线'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['general', 'business'],
      styles: ['minimal'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  qianyao: {
    id: 'qianyao',
    name: '浅曜',
    description: '厚线文档页眉与中英细线章节，基础信息独立分区',
    preview: '/thumbnails/template_qianyao.webp',
    tags: ['参考改编', '专业', '黑白', '细线'],
    taxonomy: {
      stages: ['experienced'],
      roles: ['general', 'business'],
      styles: ['minimal', 'formal'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  jilan: {
    id: 'jilan',
    name: '霁蓝',
    description: '蓝色左侧栏与六边形章节标记，履历和补充信息分栏',
    preview: '/thumbnails/template_jilan.webp',
    tags: ['参考改编', '双栏', '蓝白', '商务'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['general', 'business'],
      styles: ['formal', 'business'],
      layouts: ['double'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  qinglan: {
    id: 'qinglan',
    name: '青澜',
    description: '左侧头像与薄荷色信息带，方形图标单栏章节',
    preview: '/thumbnails/template_qinglan.webp',
    tags: ['参考改编', '校招', '薄荷', '单栏'],
    taxonomy: {
      stages: ['graduate', 'internship'],
      roles: ['general', 'business'],
      styles: ['fresh'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  yinxing: {
    id: 'yinxing',
    name: '银杏',
    description: '圆形头像与右侧信息栏，黑色胶囊标题搭配浅色角饰',
    preview: '/thumbnails/template_yinxing.webp',
    tags: ['参考改编', '右侧栏', '圆形头像', '清爽'],
    taxonomy: {
      stages: ['experienced'],
      roles: ['general', 'business'],
      styles: ['fresh', 'minimal'],
      layouts: ['double'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  jinshu: {
    id: 'jinshu',
    name: '锦书',
    description: '灰蓝折角标题与点线纵轴，清晰的单栏履历层级',
    preview: '/thumbnails/template_jinshu.webp',
    tags: ['参考改编', '灰蓝', '折角', '点线'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['general', 'business'],
      styles: ['classic', 'fresh'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  liuguang: {
    id: 'liuguang',
    name: '流光',
    description: '深灰蓝切角页眉与双色斜切章节条，单栏专业版式',
    preview: '/thumbnails/template_liuguang.webp',
    tags: ['参考改编', '切角', '灰蓝', '单栏'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['business', 'creative'],
      styles: ['business', 'minimal'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  mingxu: {
    id: 'mingxu',
    name: '明序',
    description: '厚线文档页眉与黑底方形图标，灰阶单栏履历',
    preview: '/thumbnails/template_mingxu.webp',
    tags: ['参考改编', '灰阶', '图标', '商务'],
    taxonomy: {
      stages: ['experienced'],
      roles: ['general', 'business'],
      styles: ['business', 'minimal'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  guanlan: {
    id: 'guanlan',
    name: '观澜',
    description: '深蓝外框与圆形章节标记，点线分隔的正式单栏',
    preview: '/thumbnails/template_guanlan.webp',
    tags: ['参考改编', '正式', '外框', '深蓝'],
    taxonomy: {
      stages: ['experienced', 'executive'],
      roles: ['general', 'business'],
      styles: ['formal', 'minimal'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  chujian: {
    id: 'chujian',
    name: '初见',
    description: '书签角饰与灰蓝旗形标题，基础信息独立的校招单栏',
    preview: '/thumbnails/template_chujian.webp',
    tags: ['参考改编', '校招', '旗形标题', '灰蓝'],
    taxonomy: {
      stages: ['graduate', 'internship'],
      roles: ['general', 'education'],
      styles: ['fresh', 'classic'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  chunzhao: {
    id: 'chunzhao',
    name: '春招',
    description: '纵向简历页签与浅蓝圆角章节条，清爽校招单栏',
    preview: '/thumbnails/template_chunzhao.webp',
    tags: ['参考改编', '校招', '纵向页签', '浅蓝'],
    taxonomy: {
      stages: ['graduate', 'internship'],
      roles: ['general', 'business'],
      styles: ['fresh'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  xingmiao: {
    id: 'xingmiao',
    name: '星苗',
    description: '拍立得头像与胶带标题的拼贴双栏，适合创意校招',
    preview: '/thumbnails/template_xingmiao.webp',
    tags: ['参考改编', '校招', '拼贴', '双栏'],
    taxonomy: {
      stages: ['graduate', 'internship'],
      roles: ['creative', 'business'],
      styles: ['creative'],
      layouts: ['double'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  jianqing: {
    id: 'jianqing',
    name: '简擎',
    description: '三圆角饰与黑色梯形章节页签，黑白校招单栏',
    preview: '/thumbnails/template_jianqing.webp',
    tags: ['参考改编', '校招', '黑白', '页签'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['technical'],
      styles: ['minimal', 'business'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    // 与极简黑同构，保留旧简历兼容，不重复占用公开名额。
    visibility: { editor: true, catalog: false },
  },
  qihang: {
    id: 'qihang',
    name: '启航',
    description: '紧凑蓝色页眉与三角点线章节，清晰的校招单栏',
    preview: '/thumbnails/template_qihang.webp',
    tags: ['参考改编', '校招', '三角标记', '蓝色'],
    taxonomy: {
      stages: ['graduate', 'internship'],
      roles: ['general', 'business'],
      styles: ['business', 'fresh'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  xiaoyuanlan: {
    id: 'xiaoyuanlan',
    name: '校园蓝',
    description: '灰阶文档页眉与描边图标，章末细线分隔的校招单栏',
    preview: '/thumbnails/template_xiaoyuanlan.webp',
    tags: ['参考改编', '校招', '灰阶', '描边图标'],
    taxonomy: {
      stages: ['graduate', 'internship'],
      roles: ['general', 'education'],
      styles: ['formal', 'business'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  shaoniangan: {
    id: 'shaoniangan',
    name: '少年感',
    description: '大头像和青蓝信息分区页眉，双色标题的校园双栏',
    preview: '/thumbnails/template_shaoniangan.webp',
    tags: ['参考改编', '校招', '分区页眉', '双栏'],
    taxonomy: {
      stages: ['graduate', 'internship'],
      roles: ['general', 'creative'],
      styles: ['fresh', 'creative'],
      layouts: ['double'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  zhanxu: {
    id: 'zhanxu',
    name: '展序',
    description: '左侧头像叠置蓝色信息横幅，胶囊标题和连线章节',
    preview: '/thumbnails/template_zhanxu.webp',
    tags: ['参考改编', '技术', '横幅', '单栏'],
    taxonomy: {
      stages: ['experienced'],
      roles: ['technical', 'business'],
      styles: ['business', 'fresh'],
      layouts: ['single'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  jikebai: {
    id: 'jikebai',
    name: '极客白',
    description: '斜切灰色页眉、整宽章节条与左侧日期轨道，清楚展示技术履历',
    preview: '/thumbnails/template_jikebai.webp',
    tags: ['参考改编', '技术', '灰阶', '紧凑'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['technical'],
      styles: ['minimal', 'business'],
      layouts: ['single'],
      densities: ['compact'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  heiyao: {
    id: 'heiyao',
    name: '黑曜',
    description: '黑色左侧栏与圆形头像，强调线标题的专业双栏',
    preview: '/thumbnails/template_heiyao.webp',
    tags: ['参考改编', '技术', '黑白', '双栏'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['technical', 'general'],
      styles: ['formal', 'minimal'],
      layouts: ['double'],
      densities: ['compact'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  shujuliu: {
    id: 'shujuliu',
    name: '数据流',
    description: '浅蓝窄侧栏与主栏头像页眉，圆角蓝色章节条',
    preview: '/thumbnails/template_shujuliu.webp',
    tags: ['参考改编', '技术', '侧栏', '双栏'],
    taxonomy: {
      stages: ['graduate', 'experienced'],
      roles: ['technical'],
      styles: ['business', 'minimal'],
      layouts: ['double'],
      densities: ['compact'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  jiagoushi: {
    id: 'jiagoushi',
    name: '架构师',
    description: '深灰蓝切角页眉与箭头章节条，紧凑项目单栏',
    preview: '/thumbnails/template_jiagoushi.webp',
    tags: ['参考改编', '技术', '项目', '箭头标题'],
    taxonomy: {
      stages: ['experienced', 'executive'],
      roles: ['technical', 'business'],
      styles: ['business', 'formal'],
      layouts: ['single'],
      densities: ['compact'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  zixunhui: {
    id: 'zixunhui',
    name: '咨询灰',
    description: '米色角饰与细线左侧栏，棕色圆点标题的咨询双栏',
    preview: '/thumbnails/template_zixunhui.webp',
    tags: ['参考改编', '咨询', '米色', '双栏'],
    taxonomy: {
      stages: ['experienced', 'executive'],
      roles: ['business', 'general'],
      styles: ['formal', 'minimal'],
      layouts: ['double'],
      densities: ['standard'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  caiwulan: {
    id: 'caiwulan',
    name: '财务简',
    description: '居中姓名与横向联系方式，机构、职责、日期三列台账式财务简历',
    preview: '/thumbnails/template_caiwulan.webp',
    tags: ['参考改编', '财务', '黑白', '紧凑'],
    taxonomy: {
      stages: ['experienced'],
      roles: ['business', 'general'],
      styles: ['formal', 'business'],
      layouts: ['single'],
      densities: ['compact'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
  fawujian: {
    id: 'fawujian',
    name: '法务简',
    description: '大号双行英文页眉与灰色章节条，正式细线双栏',
    preview: '/thumbnails/template_fawujian.webp',
    tags: ['参考改编', '法务', '灰阶', '双栏'],
    taxonomy: {
      stages: ['experienced', 'executive'],
      roles: ['general', 'business'],
      styles: ['formal', 'minimal'],
      layouts: ['double'],
      densities: ['compact'],
      languages: ['zh'],
    },
    visibility: { editor: true, catalog: true },
  },
} as const satisfies Record<string, TemplateMetadata>

export const templateMetadata: readonly TemplateMetadata[] =
  Object.values(TEMPLATE_METADATA)
